title: Your Site Title
description: Your site description
baseurl: "" # the subpath of your site, e.g. /blog - leave blank for root domain

# Build settings
theme: minima # You can change this to a different theme or remove it
plugins:
  - jekyll-feed

# SCSS settings
sass:
  sass_dir: assets/css # SCSS 파일이 있는 디렉토리를 지정합니다.
  style: compressed
